version: 2
updates:
  - package-ecosystem: cargo
    directory: /desktop
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /server
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /viewer
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /simulator
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /graphics
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /worker_builder
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /worker_simulator
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /api
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /runner
    schedule:
      interval: daily            
  - package-ecosystem: "docker"
    directory: "/scripts/Dockerfiles/dart.Dockerfile"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/scripts/Dockerfiles/go.Dockerfile"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/scripts/Dockerfiles/java.Dockerfile"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/scripts/Dockerfiles/js.Dockerfile"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/scripts/Dockerfiles/py.Dockerfile"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/scripts/Dockerfiles/rs.Dockerfile"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/web"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/worker_builder"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/worker_simulator"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "daily"