version: 2
updates:
  - package-ecosystem: cargo
    directory: /desktop
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /server
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /viewer
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /engine
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /graphics
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /worker_builder
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /worker_simulator
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /api
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /runner
    schedule:
      interval: daily            
  - package-ecosystem: "docker"
    directory: "/scripts/Dockerfiles/dart"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/scripts/Dockerfiles/go"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/scripts/Dockerfiles/java"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/scripts/Dockerfiles/js"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/scripts/Dockerfiles/py"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/scripts/Dockerfiles/rs"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/web"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/worker_builder"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/worker_simulator"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "daily"