[workspace]

members = [
    "api",
    "cli",
    "desktop",
    "runner",
    "server",
    "simulator",
    "simulator_graphics",
    "viewer",
    "worker_builder",
    "worker_simulator"
]

resolver = "2"