version: "3.9"
services:
  server:
    container_name: server
    build:
      context: packages/server
    restart: unless-stopped
    ports:
      - 8089:8088
    environment:
      - DB_URL=postgres://postgres:example@db:5432
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ctserver
    links:
      - "db"
      - "ocypod:mq"

  builder:
    container_name: builder
    build:
      context: packages/builder
    command: ctbuilder
    links:
      - "db"
      - "ocypod:mq"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./test/postgres:/var/lib/postgresql/data

  ocypod:
    container_name: ocypod
    image: davechallis/ocypod:latest
    volumes:
      - ./ocypod.toml:/etc/ocypod.toml:ro
    command: /etc/ocypod.toml
    ports:
      - 8023:8023

  ocypod-redis:
    container_name: ocypod-redis
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - ./test/redis:/data

  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin