version: "3.9"
services:
  server:
    container_name: server
    image: ghcr.io/derrick56007/codetanks_server:latest
    restart: unless-stopped
    ports:
      - 8089:8088
    environment:
      - DB_URL=postgres://postgres:example@db:5432
    command: ctserver
  
  builder:
    container_name: builder
    image: ghcr.io/derrick56007/codetanks_worker_builder:latest
    # build:
    #   dockerfile: worker_builder/Dockerfile
    #   context: .
    command: ctbuilder
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DB_URL=postgres://postgres:example@db:5432

  simulator:
    container_name: simulator
    image: ghcr.io/derrick56007/codetanks_worker_simulator:latest
    # build:
    #   dockerfile: worker_simulator/Dockerfile
    #   context: .
    command: ctsim
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
    environment:
      - DB_URL=postgres://postgres:example@db:5432

  web:
    container_name: web
    image: ghcr.io/derrick56007/codetanks_web:latest
    # build:
    #   dockerfile: web/Dockerfile
    #   context: .
    restart: unless-stopped
    ports:
      - 8088:8080

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./test/postgres:/var/lib/postgresql/data

  ocypod:
    container_name: ocypod
    image: davechallis/ocypod:latest
    volumes:
      - ./ocypod.toml:/etc/ocypod.toml:ro
    command: /etc/ocypod.toml
    ports:
      - 8023:8023
    restart: always

  ocypod-redis:
    container_name: ocypod-redis
    image: redis:6
    ports:
      - 6379:6379
    # volumes:
    #   - ./test/redis:/data
    restart: always

  registry:
    container_name: registry
    image: registry
    restart: always
    ports:
      - 5001:5001
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5001
    volumes:
      - ./test/registry/:/var/lib/registry

  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin