version: "3.9"
services:
  server:
    container_name: server
    image: ghcr.io/code-tanks/code-tanks-server:latest
    restart: unless-stopped
    ports:
      - 8089:8088
    environment:
      - DB_URL=postgres://postgres:example@db:5432
    command: ctserver
  
  builder:
    image: ghcr.io/code-tanks/code-tanks-builder:latest
    command: ctbuilder
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DB_URL=postgres://postgres:example@db:5432
    deploy:
      replicas: 2

  simulator:
    image: ghcr.io/code-tanks/code-tanks-simulator:latest
    command: ctsim
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
    environment:
      - DB_URL=postgres://postgres:example@db:5432
    deploy:
      replicas: 2
      
  web:
    container_name: web
    image: ghcr.io/code-tanks/code-tanks-web:latest
    restart: unless-stopped
    ports:
      - 8098:8080

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./test/postgres:/var/lib/postgresql/data

  ocypod:
    container_name: ocypod
    image: davechallis/ocypod:latest
    volumes:
      - ./ocypod.toml:/etc/ocypod.toml:ro
    command: /etc/ocypod.toml
    ports:
      - 8023:8023
    restart: always

  ocypod-redis:
    container_name: ocypod-redis
    image: redis:6
    ports:
      - 6379:6379
    # volumes:
    #   - ./test/redis:/data
    restart: always

  registry:
    container_name: registry
    image: registry
    restart: always
    ports:
      - 5001:5001
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5001
    volumes:
      - ./test/registry/:/var/lib/registry

  hoster:
    container_name: hoster
    image: dvdarias/docker-hoster
    restart: always
    volumes:
      - /etc/hosts:/tmp/hosts
      - /var/run/docker.sock:/tmp/docker.sock

  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin