version: "3.9"
services:
  server:
    container_name: server
    image: ghcr.io/code-tanks/code-tanks-server:latest
    restart: unless-stopped
    ports:
      - 8089:8088
    environment:
      - DB_URL=postgres://postgres:example@db:5432
    command: ctserver
    networks:
      - no-internet
      - internet
    # depends_on:
    #   - builder
    #   - simulator

  builder:
    image: ghcr.io/code-tanks/code-tanks-builder:latest
    command: ctbuilder
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DB_URL=postgres://postgres:example@db:5432
    deploy:
      replicas: 2
    networks:
      - no-internet
      - internet
    # depends_on:
    #   - db
    #   - ocypod
      # - registry

  simulator:
    image: ghcr.io/code-tanks/code-tanks-simulator:latest
    command: ctsim
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
    environment:
      - DB_URL=postgres://postgres:example@db:5432
    deploy:
      replicas: 2
    networks:
      - no-internet
    # depends_on:
    #   - db
    #   - ocypod
      # - registry
  
  web:
    container_name: web
    image: ghcr.io/code-tanks/code-tanks-web:latest
    restart: unless-stopped
    ports:
      - 8098:8080
    networks:
      - no-internet
      - internet
    # depends_on:
    #   - server

  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432
    # volumes:
    #   - ./test/postgres:/var/lib/postgresql/data
    networks:
      - no-internet

  ocypod:
    container_name: ocypod
    image: davechallis/ocypod:latest
    volumes:
      - ./ocypod.toml:/etc/ocypod.toml:ro
    command: /etc/ocypod.toml
    ports:
      - 8023
    restart: unless-stopped
    networks:
      - no-internet
    # depends_on:
    #   - ocypod-redis

  ocypod-redis:
    container_name: ocypod-redis
    image: redis:6
    ports:
      - 6379
    # volumes:
    #   - ./test/redis:/data
    restart: unless-stopped
    networks:
      - no-internet

  registry:
    container_name: registry
    image: registry
    restart: unless-stopped
    ports:
      - 5001
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5001
    # volumes:
    #   - ./test/registry/:/var/lib/registry
    networks:
      - no-internet
      - internet

  # pgAdmin:
  #   container_name: pgAdmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - 8081:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   networks:
  #     - no-internet
  #     - internet

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge