[package]
name = "ctsim"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = "0.8.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"

[[bin]]
name = "ctsim"
path = "src/main.rs"

[[bin]]
name = "test"
path = "src/test.rs"