[package]
name = "ctbuilder"
version = "0.1.0"
edition = "2021"

[dependencies]
ctbuilderlib = { path = "lib" }

[[bin]]
name = "ctbuilder"
path = "src/main.rs"

[[bin]]
name = "test"
path = "src/test.rs"