[package]
name = "ctserver"
version = "0.1.2"
edition = "2021"

[dependencies]
futures = "0.3.26"
r2d2_postgres = "0.18.1"
async-std = { version = "1.12.0", features = [ "attributes" ] }

[[bin]]
name = "ctserver"
path = "src/main.rs"
