[package]
name = "ctserver"
version = "0.1.0"
edition = "2021"

[dependencies]
ctserverlib = { path = "lib" }

[[bin]]
name = "ctserver"
path = "src/main.rs"

[[bin]]
name = "test"
path = "src/test.rs"