[package]
name = "ctbuilder"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
postgres = "0.19.3"

[[bin]]
name = "ctbuilder"
path = "src/main.rs"

[[bin]]
name = "test"
path = "src/test.rs"