name: build

on:
  push:
    branches:
      - main
    paths:
      - server/**
      - simulator/**
      - simulator_graphis/**
      - desktop/**
      - viewer/**
      - worker_builder/**
      - worker_simulator/**
      - web/**
      - .github/workflows/build.yml

jobs:
  build_worker_builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: worker_builder/Dockerfile
          push: true
          tags: ghcr.io/derrick56007/code-tanks-builder:latest
          cache-from: type=registry,ref=ghcr.io/derrick56007/code-tanks-builder:buildcache
          cache-to: type=registry,ref=ghcr.io/derrick56007/code-tanks-builder:buildcache,mode=max

  build_worker_simulator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: worker_simulator/Dockerfile
          push: true
          tags: ghcr.io/derrick56007/code-tanks-simulator:latest
          cache-from: type=registry,ref=ghcr.io/derrick56007/code-tanks-simulator:buildcache
          cache-to: type=registry,ref=ghcr.io/derrick56007/code-tanks-simulator:buildcache,mode=max

  build_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: server/Dockerfile
          push: true
          tags: ghcr.io/derrick56007/code-tanks-server:latest
          cache-from: type=registry,ref=ghcr.io/derrick56007/code-tanks-server:buildcache
          cache-to: type=registry,ref=ghcr.io/derrick56007/code-tanks-server:buildcache,mode=max

  build_web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: web/Dockerfile
          push: true
          tags: ghcr.io/derrick56007/code-tanks-web:latest
          cache-from: type=registry,ref=ghcr.io/derrick56007/code-tanks-web:buildcache
          cache-to: type=registry,ref=ghcr.io/derrick56007/code-tanks-web:buildcache,mode=max

  # build_linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     - name: Log in to the Container registry
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: .
  #         file: desktop/Dockerfile
  #         push: true
  #         tags: ghcr.io/derrick56007/code-tanks_linux:latest
  #         cache-from: type=registry,ref=ghcr.io/derrick56007/code-tanks_linux:buildcache
  #         cache-to: type=registry,ref=ghcr.io/derrick56007/code-tanks_linux:buildcache,mode=max