name: build

on:
  push:
    branches:
      - "main"
    paths:
      - server
      - simulator
      - viewer
      - worker_builder
      - worker_simulator

jobs:
  build_worker_builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: worker_builder/Dockerfile
          push: true
          tags: ghcr.io/derrick56007/codetanks_worker_builder:latest
          cache-from: type=registry,ref=ghcr.io/derrick56007/codetanks_worker_builder:buildcache
          cache-to: type=registry,ref=ghcr.io/derrick56007/codetanks_worker_builder:buildcache,mode=max

  build_worker_simulator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: worker_simulator/Dockerfile
          push: true
          tags: ghcr.io/derrick56007/codetanks_worker_simulator:latest
          cache-from: type=registry,ref=ghcr.io/derrick56007/codetanks_worker_simulator:buildcache
          cache-to: type=registry,ref=ghcr.io/derrick56007/codetanks_worker_simulator:buildcache,mode=max

  build_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: server/Dockerfile
          push: true
          tags: ghcr.io/derrick56007/codetanks_server:latest
          cache-from: type=registry,ref=ghcr.io/derrick56007/codetanks_server:buildcache
          cache-to: type=registry,ref=ghcr.io/derrick56007/codetanks_server:buildcache,mode=max
