name: ci-dev

on:
  workflow_run:
    workflows: ["build-dev"]
    types:
      - completed
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - .github/workflows/ci-dev.yml
  #     - api/**
  #     - cli/**
  #     # - desktop/**
  #     - runner/**
  #     - server/**
  #     - simulator/**
  #     - simulator_graphics/**
  #     - viewer/**
  #     - web/**
  #     - worker_builder/**
  #     - worker_simulator/**
  #     - scripts/**
  #     - docker-compose.yml
  #     - ocypod.toml

jobs:
  test:
    runs-on: self-hosted
    services:
      all:
        image: ghcr.io/code-tanks/code-tanks-all-dev:latest
        ports:
          - 8089:8088
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        env:
          DB_URL: postgres://postgres:postgres@localhost:5432
          OCYPOD_URL: localhost:8023
      registry:
        image: registry
        ports:
          - 5001:5001
        env:
          REGISTRY_HTTP_ADDR: 0.0.0.0:5001

    steps:
      - uses: actions/checkout@v3
      # - name: "install curl"
      #   run: |
      #     apt update
      #     DEBIAN_FRONTEND=noninteractive apt install -y curl
      - name: "pull dart"
        run: docker pull dart:stable
      - name: "sleep"
        run: sleep 30
      - name: "test server"
        run: curl -s localhost:8089/ping
      - name: "Test do_nothing"
        run: |
          echo "HOST=localhost:8089" > ./scripts/.env
          ./scripts/test/test_do_nothing.sh

        # run: script -e -c "./scripts/test/test_do_nothing.sh"
      