name: ci

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - api/**
      - cli/**
      - desktop/**
      - runner/**
      - server/**
      - simulator/**
      - simulator_graphics/**
      - viewer/**
      - web/**
      - worker_builder/**
      - worker_simulator/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up environment"
        run: ./scripts/dev/build_all.sh
        run: docker compose up -d
      