name: ci

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - api/**
      - cli/**
      - desktop/**
      - runner/**
      - server/**
      - simulator/**
      - simulator_graphics/**
      - viewer/**
      - web/**
      - worker_builder/**
      - worker_simulator/**
      - scripts/test/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Pull images"
        run: docker compose pull     
      - name: "Build"
        run: ./scripts/dev/build_all.sh
      - name: "Set up environment"
        run: docker compose up -d
      - name: "Setup Env"
        run: echo "HOST=http://localhost:8089" > ./scripts/.env
      - name: "Test Upload Examples"
        run: ./scripts/official/upload_tanks.sh examples/
      - name: "Test do_nothing"
        run: ./scripts/test/test_do_nothing.sh
      