name: ci

on:
  workflow_run:
    workflows: ["build-dev"]
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - scripts/test/**
      - docker-compose.yml
      - ocypod.toml
      # - 
      # - up.sh
  #     - api/**
  #     - cli/**
  #     # - desktop/**
  #     - runner/**
  #     - server/**
  #     - simulator/**
  #     - graphics/**
  #     - viewer/**
  #     - web/**
  #     - worker_builder/**
  #     - worker_simulator/**

jobs:
  test_do_nothing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "up"
        run: docker compose up -d
      - name: "pull dart image"
        run: docker pull dart:stable
      - name: "sleep"
        run: sleep 10
      - name: "ping"
        run: curl -s localhost:8089/ping
      # - name: "setup env"
      #   run: echo "HOST=localhost:8089" > ./scripts/.env
      - name: "test_do_nothing.sh"
        run: ./scripts/test/test_do_nothing.sh
  test_spin_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "up"
        run: docker compose up -d
      - name: "pull dart image"
        run: docker pull dart:stable
      - name: "sleep"
        run: sleep 10
      - name: "ping"
        run: curl -s localhost:8089/ping
      - name: "test_spin_bot.sh"
        run: ./scripts/test/test_spin_bot.sh

        # run: script -e -c "./scripts/test/test_do_nothing.sh"
  test_timeout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "up"
        run: docker compose up -d
      - name: "pull dart image"
        run: docker pull dart:stable
      - name: "sleep"
        run: sleep 10
      - name: "ping"
        run: curl -s localhost:8089/ping
      - name: "test_spin_bot.sh"
        run: ./scripts/test/test_timeout.sh

  test_forward_one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "up"
        run: docker compose up -d
      - name: "pull dart image"
        run: docker pull dart:stable
      - name: "sleep"
        run: sleep 10
      - name: "ping"
        run: curl -s localhost:8089/ping
      - name: "test_spin_bot.sh"
        run: ./scripts/test/test_forward_one.sh

  test_rotate_one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "up"
        run: docker compose up -d
      - name: "pull dart image"
        run: docker pull dart:stable
      - name: "sleep"
        run: sleep 10
      - name: "ping"
        run: curl -s localhost:8089/ping
      - name: "test_spin_bot.sh"
        run: ./scripts/test/test_rotate_one.sh