name: ci

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - api/**
      - cli/**
      # - desktop/**
      - runner/**
      - server/**
      - simulator/**
      - simulator_graphics/**
      - viewer/**
      - web/**
      - worker_builder/**
      - worker_simulator/**
      - scripts/**
      - docker-compose.yml
      - ocypod.toml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Pull images"
        run: docker compose pull     
      - name: "Pull curl"
        run: docker pull curlimages/curl:7.80.0
      - name: "Pull dart"
        run: docker pull dart:stable
      - name: "Set up environment"
        run: docker compose up -d
      - name: "Set up environment 2"
        run: sleep 10
      - name: "Set up environment 3"
        run: docker compose ps
      # - name: "Setup Env"
      #   run: echo "HOST=http://localhost:8089" > ./scripts/.env
      # - name: "Test Upload Examples"
      #   run: ./scripts/upload_tanks.sh examples/
      - name: "Test do_nothing"
        run: ./scripts/test/test_do_nothing.sh
        # run: script -e -c "./scripts/test/test_do_nothing.sh"
      