name: ci

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - api/**
      - cli/**
      # - desktop/**
      - runner/**
      - server/**
      - simulator/**
      - simulator_graphics/**
      - viewer/**
      - web/**
      - worker_builder/**
      - worker_simulator/**
      - scripts/**
      - docker-compose.yml
      - ocypod.toml

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      all:
        image: ghcr.io/code-tanks/code-tanks-all:latest
        ports:
          - 8089:8088
      registry:
        image: registry
        ports:
          - 5001:5001
        env:
          REGISTRY_HTTP_ADDR: 0.0.0.0:5001

    steps:
      - uses: actions/checkout@v3
      # - name: "install curl"
      #   run: |
      #     apt update
      #     DEBIAN_FRONTEND=noninteractive apt install -y curl
      - name: "test server"
        run: sleep 60
      - name: "test server"
        run: curl localhost:8089/ping
      - name: "Test do_nothing"
        run: |
          echo "HOST=localhost:8089" > ./scripts/.env
          ./scripts/test/test_do_nothing.sh

        # run: script -e -c "./scripts/test/test_do_nothing.sh"
      