name: examples

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/examples.yml
      - examples/**
      - scripts/build.sh
      - scripts/Dockerfiles/**
      - scripts/test/test_examples.sh

jobs:
  build_examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/test/test_examples.sh