name: examples

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/examples.yml
      - examples/**
      - scripts/build.sh
      - scripts/Dockerfiles/**

jobs:
  build_examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-cargo-build-examples-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: for i in examples/*/**; do ./scripts/build.sh $i; done