name: test

# on:
#   workflow_run:
#     workflows: ["build"]
#     types:
#       - completed
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      image: ghcr.io/derrick56007/codetanks_server:latest
      ports:
        - 8089:8088
      environment:
        - DB_URL=postgres://postgres:example@db:5432
      command: ctserver

    steps:
        run: |
          curl localhost:8089/ping
# ./scripts/create_dart_starter.sh dart
# curl --data-binary "@dart/examples/do_nothing_tank.dart" -H 'Content-Type: text/plain' -X POST localhost:8089/upload
