name: test

# on:
#   workflow_run:
#     workflows: ["build"]
#     types:
#       - completed
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: |
          docker ps -a
          ./scripts/create_dart_starter.sh dart
          curl 0.0.0.0:8089/ping
          curl --data-binary "@dart/examples/do_nothing_tank.dart" -H 'Content-Type: text/plain' -X POST localhost:8089/upload
