name: test

# on:
#   workflow_run:
#     workflows: ["build"]
#     types:
#       - completed
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      # server:
        # image: ghcr.io/derrick56007/codetanks_server:latest
        # ports:
        #   - 8088:8088
        # env:
        #   DB_URL: postgres://postgres:example@db:5432
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: example
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          docker run -d -p 8088:8088 -e DB_URL=postgres://postgres:example@db:5432 ghcr.io/derrick56007/codetanks_server:latest
          apt update && apt install -y curl
          curl localhost:8088/ping
# ./scripts/create_dart_starter.sh dart
# curl --data-binary "@dart/examples/do_nothing_tank.dart" -H 'Content-Type: text/plain' -X POST localhost:8089/upload
