name: test

on:
  push:
    branches:
      - main
    paths:
      - server/**
      - simulator/**
      - viewer/**
      - worker_builder/**
      - worker_simulator/**
      - web/**
      - .github/workflows/test.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose up -d