name: test

# on:
#   workflow_run:
#     workflows: ["build"]
#     types:
#       - completed
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          apt update && apt install -y curl git build-essential pkg-config libssl-dev
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          docker compose up -d db ocypod-redis registry pgAdmin
          docker run -d -p 8023:8023 -v $PWD/ocypod.toml --name ocypod --network=codetanks_default davechallis/ocypod:latest /etc/ocypod.toml
          sleep 10
          docker compose up -d
          sleep 5
          docker ps -a
          docker logs ocypod
          docker logs server
          curl localhost:8089/ping
# ./scripts/create_dart_starter.sh dart
# curl --data-binary "@dart/examples/do_nothing_tank.dart" -H 'Content-Type: text/plain' -X POST localhost:8089/upload
